"""Binary Sensor platform for elegoo_printer."""

from __future__ import annotations

from typing import TYPE_CHECKING

from homeassistant.components.binary_sensor import (
    BinarySensorEntity,
)

from .const import LOGGER
from .definitions import (
    PRINTER_ATTRIBUTES_BINARY_COMMON,
    PRINTER_ATTRIBUTES_BINARY_V3_ONLY,
    PRINTER_BINARY_STATUS_CANVAS,
    PRINTER_BINARY_STATUS_RESIN_VAT_HEATER,
    ElegooPrinterBinarySensorEntityDescription,
)
from .entity import ElegooPrinterEntity
from .sdcp.models.enums import PrinterType, ProtocolVersion

if TYPE_CHECKING:
    from homeassistant.core import HomeAssistant
    from homeassistant.helpers.entity_platform import AddEntitiesCallback

    from .coordinator import ElegooDataUpdateCoordinator
    from .data import ElegooPrinterConfigEntry


async def async_setup_entry(
    hass: HomeAssistant,  # noqa: ARG001
    entry: ElegooPrinterConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the binary sensor platform."""
    coordinator: ElegooDataUpdateCoordinator = entry.runtime_data.coordinator
    printer = coordinator.config_entry.runtime_data.api.printer
    printer_type = printer.printer_type
    protocol_version = printer.protocol_version

    sensors: list[ElegooPrinterBinarySensorEntityDescription] = []

    # Common binary sensors (both V1 and V3)
    sensors.extend(PRINTER_ATTRIBUTES_BINARY_COMMON)

    # V3-only binary sensors (WebSocket/SDCP printers)
    if protocol_version == ProtocolVersion.V3:
        sensors.extend(PRINTER_ATTRIBUTES_BINARY_V3_ONLY)

    # Canvas/AMS binary sensors (CC2 FDM with Canvas support)
    if printer_type == PrinterType.FDM and protocol_version == ProtocolVersion.CC2:
        sensors.extend(PRINTER_BINARY_STATUS_CANVAS)

    # Vat heater specific binary sensors
    if printer_type == PrinterType.RESIN and printer.has_vat_heater:
        sensors.extend(PRINTER_BINARY_STATUS_RESIN_VAT_HEATER)

    LOGGER.debug(
        f"Adding {len(sensors)} binary sensor entities for "
        f"{protocol_version.value} printer"
    )
    async_add_entities(
        [
            ElegooPrinterBinarySensor(
                coordinator=coordinator,
                entity_description=entity_description,
            )
            for entity_description in sensors
        ],
        update_before_add=True,
    )


class ElegooPrinterBinarySensor(ElegooPrinterEntity, BinarySensorEntity):
    """elegoo_printer binary_sensor class."""

    def __init__(
        self,
        coordinator: ElegooDataUpdateCoordinator,
        entity_description: ElegooPrinterBinarySensorEntityDescription,
    ) -> None:
        """Initialize the binary_sensor class."""
        super().__init__(coordinator)
        self.entity_description = entity_description
        self._attr_unique_id = coordinator.generate_unique_id(
            self.entity_description.key
        )

    @property
    def extra_state_attributes(self) -> dict:
        """
        Returns additional state attributes for the binary sensor.

        The attributes are generated by the entity descriptions extra_attributes method.
        """
        return self.entity_description.extra_attributes(self)

    @property
    def is_on(self) -> bool:
        """Return true if the binary_sensor is on."""
        if self.coordinator.data:
            return self.entity_description.value_fn(self.coordinator.data)
        return False
