"""Constants for CC2 (Centauri Carbon 2) protocol implementation."""

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

# Discovery settings
CC2_DISCOVERY_PORT = 52700
CC2_DISCOVERY_MESSAGE = {"id": 0, "method": 7000}
CC2_DISCOVERY_TIMEOUT = 10  # Increased for slower networks/printers
CC2_DISCOVERY_RETRIES = 2  # Number of broadcast attempts

# MQTT settings (printer runs broker)
CC2_MQTT_PORT = 1883
CC2_MQTT_KEEPALIVE = 60
CC2_MQTT_USERNAME = "elegoo"
CC2_MQTT_DEFAULT_PASSWORD = "123456"  # noqa: S105

# Heartbeat settings
CC2_HEARTBEAT_INTERVAL = 10  # seconds
CC2_HEARTBEAT_TIMEOUT = 65  # seconds

# Registration settings
CC2_REGISTRATION_TIMEOUT = 3  # seconds

# Command timeout
CC2_COMMAND_TIMEOUT = 10  # seconds

# Delta status settings
CC2_MAX_NON_CONTINUOUS_EVENTS = 5  # Re-request full status after this many gaps
# Max distinct print-status snapshots queued for HA replay (MQTT bursts)
CC2_PRINT_STATUS_TRANSITION_QUEUE_MAX = 32

# Topic patterns
# elegoo/<sn>/api_register - Registration request
# elegoo/<sn>/<request_id>/register_response - Registration acknowledgment
# elegoo/<sn>/<client_id>/api_request - Commands (publish)
# elegoo/<sn>/<client_id>/api_response - Responses (subscribe)
# elegoo/<sn>/api_status - Status updates (subscribe)

# Command IDs (from elegoo-link COMMAND_MAPPING_TABLE)
CC2_CMD_GET_ATTRIBUTES = 1001
CC2_CMD_GET_STATUS = 1002
CC2_CMD_START_PRINT = 1020
CC2_CMD_PAUSE_PRINT = 1021
CC2_CMD_STOP_PRINT = 1022
CC2_CMD_RESUME_PRINT = 1023
CC2_CMD_HOME_AXES = 1026
CC2_CMD_MOVE_AXES = 1027
CC2_CMD_SET_TEMPERATURE = 1028
CC2_CMD_SET_LIGHT = 1029
CC2_CMD_SET_FAN_SPEED = 1030
CC2_CMD_SET_PRINT_SPEED = 1031
CC2_CMD_PRINT_TASK_LIST = 1036
CC2_CMD_PRINT_TASK_DETAIL = 1037
CC2_CMD_DELETE_PRINT_TASK = 1038
CC2_CMD_VIDEO_STREAM = 1042
CC2_CMD_SET_VIDEO_STREAM = CC2_CMD_VIDEO_STREAM  # Alias for backwards compatibility
CC2_CMD_UPDATE_PRINTER_NAME = 1043
CC2_CMD_GET_FILE_LIST = 1044
CC2_CMD_GET_FILE_THUMBNAIL = 1045
CC2_CMD_GET_FILE_DETAIL = 1046
CC2_CMD_DELETE_FILE = 1047
CC2_CMD_GET_DISK_INFO = 1048
CC2_CMD_DOWNLOAD_FILE = 1057
CC2_CMD_CANCEL_DOWNLOAD = 1058

# Canvas/AMS commands
CC2_CMD_SET_AUTO_REFILL = 2004
CC2_CMD_GET_CANVAS_STATUS = 2005

# Event IDs (push notifications from printer)
CC2_EVENT_STATUS = 6000
CC2_EVENT_ATTRIBUTES = 6008

# Error codes
CC2_ERROR_SUCCESS = 0
CC2_ERROR_TOKEN_FAILED = 1000
CC2_ERROR_UNKNOWN_INTERFACE = 1001
CC2_ERROR_FOLDER_OPEN_FAILED = 1002
CC2_ERROR_INVALID_PARAMETER = 1003
CC2_ERROR_FILE_WRITE_FAILED = 1004
CC2_ERROR_TOKEN_UPDATE_FAILED = 1005
CC2_ERROR_PRINTER_BUSY = 1009
CC2_ERROR_NOT_PRINTING = 1010
CC2_ERROR_TASK_NOT_FOUND = 1012
CC2_ERROR_FILE_OFFSET_MISMATCH = 9000
CC2_ERROR_MD5_FAILED = 9004

# Registration error messages
CC2_REG_OK = "ok"
CC2_REG_FAIL = "fail"
CC2_REG_TOO_MANY_CLIENTS = "too many clients"

# Machine status codes (different from SDCP)
CC2_STATUS_INITIALIZING = 0
CC2_STATUS_IDLE = 1
CC2_STATUS_PRINTING = 2
CC2_STATUS_FILAMENT_OPERATING = 3
CC2_STATUS_FILAMENT_OPERATING_2 = 4
CC2_STATUS_AUTO_LEVELING = 5
CC2_STATUS_PID_CALIBRATING = 6
CC2_STATUS_RESONANCE_TESTING = 7
CC2_STATUS_SELF_CHECKING = 8
CC2_STATUS_UPDATING = 9
CC2_STATUS_HOMING = 10
CC2_STATUS_FILE_TRANSFERRING = 11
CC2_STATUS_VIDEO_COMPOSING = 12
CC2_STATUS_EXTRUDER_OPERATING = 13
CC2_STATUS_EMERGENCY_STOP = 14
CC2_STATUS_POWER_LOSS_RECOVERY = 15

# Sub-status codes (from elegoo-link elegoo_fdm_cc2_message_adapter.cpp)
# Common
CC2_SUBSTATUS_NONE = 0

# Printing sub-states (status=2)
CC2_SUBSTATUS_EXTRUDER_PREHEATING = 1045
CC2_SUBSTATUS_EXTRUDER_PREHEATING_2 = 1096
CC2_SUBSTATUS_BED_PREHEATING = 1405
CC2_SUBSTATUS_BED_PREHEATING_2 = 1906
CC2_SUBSTATUS_PRINTING = 2075
CC2_SUBSTATUS_PRINTING_COMPLETED = 2077
CC2_SUBSTATUS_PAUSING = 2501
CC2_SUBSTATUS_PAUSED = 2502
CC2_SUBSTATUS_PAUSED_2 = 2505
CC2_SUBSTATUS_RESUMING = 2401
CC2_SUBSTATUS_RESUMING_COMPLETED = 2402
CC2_SUBSTATUS_STOPPING = 2503
CC2_SUBSTATUS_STOPPED = 2504
CC2_SUBSTATUS_HOMING = 2801
CC2_SUBSTATUS_HOMING_COMPLETED = 2802
CC2_SUBSTATUS_AUTO_LEVELING = 2901
CC2_SUBSTATUS_AUTO_LEVELING_COMPLETED = 2902

# Filament operating sub-states (status=3,4)
CC2_SUBSTATUS_FILAMENT_LOADING = 1133
CC2_SUBSTATUS_FILAMENT_LOADING_2 = 1134
CC2_SUBSTATUS_FILAMENT_LOADING_3 = 1135
CC2_SUBSTATUS_FILAMENT_LOADING_COMPLETED = 1136
CC2_SUBSTATUS_FILAMENT_UNLOADING = 1144
CC2_SUBSTATUS_FILAMENT_UNLOADING_COMPLETED = 1145

# Auto leveling sub-states (status=5)
CC2_SUBSTATUS_AL_AUTO_LEVELING = 2901
CC2_SUBSTATUS_AL_AUTO_LEVELING_COMPLETED = 2902

# PID calibrating sub-states (status=6)
CC2_SUBSTATUS_PID_CALIBRATING = 1503
CC2_SUBSTATUS_PID_CALIBRATING_2 = 1504
CC2_SUBSTATUS_PID_CALIBRATING_COMPLETED = 1505
CC2_SUBSTATUS_PID_CALIBRATING_FAILED = 1506

# Resonance testing sub-states (status=7)
CC2_SUBSTATUS_RESONANCE_TEST = 5934
CC2_SUBSTATUS_RESONANCE_TEST_COMPLETED = 5935
CC2_SUBSTATUS_RESONANCE_TEST_FAILED = 5936

# Updating sub-states (status=9)
CC2_SUBSTATUS_UPDATING = 2071
CC2_SUBSTATUS_UPDATING_2 = 2072
CC2_SUBSTATUS_UPDATING_3 = 2073
CC2_SUBSTATUS_UPDATING_COMPLETED = 2074
CC2_SUBSTATUS_UPDATING_FAILED = 2075

# Homing sub-states (status=10)
CC2_SUBSTATUS_H_HOMING = 2801
CC2_SUBSTATUS_H_HOMING_COMPLETED = 2802
CC2_SUBSTATUS_H_HOMING_FAILED = 2803

# File transferring sub-states (status=11)
CC2_SUBSTATUS_UPLOADING_FILE = 3000
CC2_SUBSTATUS_UPLOADING_FILE_COMPLETED = 3001

# Extruder operating sub-states (status=13)
CC2_SUBSTATUS_EXTRUDER_LOADING = 1061
CC2_SUBSTATUS_EXTRUDER_UNLOADING = 1062
CC2_SUBSTATUS_EXTRUDER_LOADING_COMPLETED = 1063
CC2_SUBSTATUS_EXTRUDER_UNLOADING_COMPLETED = 1064
